version: '3'

services:
  app1: 
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "81:80"
    volumes:
      - ../:/var/www/html/app
      - ../docker/000-default.conf:/etc/apache2/sites-available/000-default.conf

  app2: 
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "82:80"
    volumes:
      - ../:/var/www/html/app
      - ../docker/000-default.conf:/etc/apache2/sites-available/000-default.conf